apiVersion: v1
kind: Service
metadata:
  name: atlas-frontend
  labels:
    app: atlas-frontend
spec:
  type: NodePort
  selector:
    app: atlas-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080