apiVersion: v1
kind: Service
metadata:
  name: atlas-service
  labels:
    app: atlas-service
spec:
  type: ClusterIP
  selector:
    app: atlas-service
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000