apiVersion: v1
kind: Service
metadata:
  name: atlas-service
  labels:
    app: atlas-service
spec:
  type: NodePort
  selector:
    app: atlas-service
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http