---
- import_playbook: deploy-application.yml

- import_playbook: deploy-frontend.yml

- name: Display deployment status
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Get deployment status
      shell: kubectl get pods,svc
      register: k8s_status

    - name: Show status
      debug:
        msg: "{{ k8s_status.stdout_lines }}"
